export  const phrases = [
    "Hello!",
    "Good props.adjt.",
    "Good props.adjt.",
    "Good props.adjt.",
    "props.subs.",
    "How are props.pron?",
    "props.pron’m props.adjt, thank props.subs.",
    "What’s props.pron name?",
    "My name is...",
    "Nice to meet props.pron.",
    "Where are props.pron from?",
    "props.pron’m from...",
    "How old are props.pron?",
    "props.pron’m... years old.",
    "Do props.pron speak props.subs?",
    "Yes, a little.",
    "Please.",
    "Thank props.subs.",
    "props.pron’re welcome.",
    "Excuse props.pron.",
    "props.pron’m sorry.",
    "What time is props.subs?",
    "It’s... o’clock.",
    "Where is the props.subs?",
    "How much is props.subs?",
    "Can props.pron help props.pron?",
    "props.pron don’t props.verb.",
    "Could props.pron repeat props.subs?",
    "What did props.pron props.verb?",
    "props.pron don’t know.",
    "props.pron like props.subs.",
    "props.pron don’t like props.subs.",
    "What’s props.subs?",
    "Where are props.pron going?",
    "Can props.pron show props.subs?",
    "What’s props.pron phone number?",
    "Can props.pron have the props.subs, please?",
    "What’s props.pron favorite props.subs?",
    "props.pron’m props.adjt.",
    "props.pron’m props.adjt.",
    "Where can props.pron find a props.subs?",
    "Let’s props.verb!",
    "Wait a moment, please.",
    "props.pron’m lost.",
    "What time does props.subs open?",
    "What time does props.subs close?",
    "props.pron’ll take props.subs.",
    "Can props.pron pay by props.subs?",
    "props.pron need a props.subs.",
    "See props.pron later."
];
